language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
install: 
    - "python setup.py install"
    - "pip install -r tests/requirements.txt"
    - "pip install coveralls"
script: "coverage run --source=tpb setup.py test"
after_success: "coveralls"
notifications:
  email: false
#after_success: "git checkout master && git merge --ff-only development && git push"
